# Generated by Django 5.2.1 on 2025-06-14 14:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testassignment_result_testassignment_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentlog',
            name='date_used',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='operation_time_minutes',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='sample_id',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='status_during_use',
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Faulty', 'Faulty'), ('Under Maintenance', 'Under Maintenance')], default='Operational', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='usage_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('samples', models.ManyToManyField(to='core.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignments', models.ManyToManyField(to='core.testassignment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('test_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.testparameter')),
            ],
        ),
    ]
