# Generated by Django 5.2.2 on 2025-06-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testparameter_price_audittrail_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignment',
            name='worksheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_assignments', to='core.worksheet'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='assignments',
            field=models.ManyToManyField(related_name='worksheets', to='core.testassignment'),
        ),
    ]
