# Generated by Django 5.2.2 on 2025-06-15 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testassignment_worksheet_worksheet_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='qc_flag',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Control', 'Control'), ('Duplicate', 'Duplicate')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(default='%', max_length=20)),
                ('parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.testparameter')),
            ],
        ),
    ]
