# Generated by Django 5.2.2 on 2025-06-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_batch_samples_remove_testresult_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='requested_parameters',
            field=models.ManyToManyField(blank=True, to='core.testparameter'),
        ),
    ]
