# Generated by Django 5.2.2 on 2025-06-15 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sample_requested_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparameter',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.testtype'),
        ),
    ]
