# Generated by Django 5.2.2 on 2025-06-15 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_testassignment_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='access_token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
