# Generated by Django 5.2.2 on 2025-06-15 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_client_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='access_token',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
