# Generated by Django 5.2.2 on 2025-06-16 09:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_client_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='access_token',
            field=models.CharField(default=core.models.generate_access_token, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
