# Generated by Django 5.2.2 on 2025-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_client_access_token_alter_client_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
